name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'TAB.Library.Frontend/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: Delete node_modules
        run: rm -rf TAB.Library.Frontend/node_modules
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_FIELD_0DA130503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "./TAB.Library.Frontend" # App source code path
          output_location: "dist" # Built app content directory
